**일변량 시각화**
- 하나의 변수로 구성된 데이터를 전체적인 관점으로 파악할 수 있는 데이터 탐색 유형 
- 단일변수 데이터를 다양한 **그래프로 시각화** 


> 시각화와 비시각화 차이?
  - 시각화: 직관적 이해 추구 
  - 비시각화: 효과적인 데이터 요약

범주형 시각화
1. 파이차트
2. 막대그래프

연속형 시각화
1. 히스토그램 
    > (한계: 구간 경계가 연속적이지 않음, 고차원 데이터에 대한 메모리 문제 발생 )
2. 커널밀도추정: 변수가 가질수 있는 모든 값의 확률을 추정 
    >(히스토그램 한계 극복)
3. 박스 플롯

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
housing_data = pd.read_excel('D:/KTdata/boston.xls')
housing_data = pd.DataFrame(housing_data)
housing_data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,CAT. MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806,0.166008
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104,0.372456
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000,0.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000,0.000000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000,0.000000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000,0.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000,1.000000

In [15]:
# 파이차트 실습
bins = [0,20,40,60,80,100]
names = ['G1','G2','G3','G4','G5']
housing_data['AGE_G5'] = pd.cut(housing_data['AGE'],bins,labels = names)
housing_data.keys()

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV', 'CAT. MEDV', 'AGE_G5'],
      dtype='object')

AGE 는 오래된 주택비율을 의미하므로 AGE G5는 오래된 주택비율 등급을 G1(0%)~ G5(100%) 추가

In [16]:
#파이차트 생성을 위해 빈도 table 생성
pie_df_G5 = pd.DataFrame(housing_data['AGE_G5'].value_counts())
# pie 차트 생성시 범주 별 크기에 따른 sorting 후 plotting
pie_df_G5

        count
AGE_G5
G5        240
G4         81
G3         76
G2         75
G1         34

In [18]:
#파이차트 생성 
pie_df_G5.plot.pie(y="AGE_G5", figsize = (10,10) , colors= sns.color_palette('hls', len(pie_df_G5)))
plt.show()

KeyError: "None of [CategoricalIndex(['G4', 'G4', 'G4', 'G3', 'G3', 'G3', 'G4', 'G5', 'G5', 'G5',\n                  ...\n                  'G4', 'G4', 'G4', 'G4', 'G4', 'G4', 'G4', 'G5', 'G5', 'G5'],\n                 categories=['G1', 'G2', 'G3', 'G4', 'G5'], ordered=True, dtype='category', length=506)] are in the [columns]"